import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:tincars/features/trips/data/chat_repository.dart';
import 'package:tincars/features/trips/domain/models/message_model.dart';

class ChatController extends AsyncNotifier<void> {
  late ChatRepository _repository;

  @override
  Future<void> build() async {
    _repository = ref.read(chatRepositoryProvider);
  }

  Future<void> sendMessage(String tripId, String text) async {
    final user = Supabase.instance.client.auth.currentUser;
    if (user == null) return;

    final message = Message(
      id: '', // Generated by DB
      tripId: tripId,
      senderId: user.id,
      text: text.trim(),
      createdAt: DateTime.now(),
    );

    state = const AsyncValue.loading();
    state = await AsyncValue.guard(() => _repository.sendMessage(message));
  }
}

final chatControllerProvider = AsyncNotifierProvider<ChatController, void>(
  () => ChatController(),
);

final tripMessagesProvider = StreamProvider.family<List<Message>, String>((
  ref,
  tripId,
) {
  return ref.read(chatRepositoryProvider).streamMessages(tripId);
});
